version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src  
      - ./.env:/usr/src/.env  
    env_file:
      - ./.env  
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/src  
      - ./.env:/usr/src/.env  
    env_file:
      - ./.env  
    environment:
      REACT_APP_GOOGLE_API_KEY :  "${REACT_APP_GOOGLE_API_KEY}"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  
      - ./my.cnf:/etc/mysql/my.cnf  

volumes:
  db_data:
