-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 11:59:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema taxi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taxi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxi` ;
USE `taxi` ;

-- -----------------------------------------------------
-- Table `taxi`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi`.`motorista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `descricao` LONGTEXT NULL,
  `carro` VARCHAR(200) NULL,
  `avaliacao` LONGTEXT NULL,
  `taxa` DOUBLE NULL,
  `km_minimo` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxi`.`viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxi`.`viagem` (
  `id` INT NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `origem` VARCHAR(255) NULL,
  `destino` VARCHAR(255) NULL,
  `distancia` INT NULL,
  `duracao` VARCHAR(100) NULL,
  `valor` DOUBLE NULL,
  `cliente_id` INT NOT NULL,
  `motorista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_viagem_motorista1_idx` (`motorista_id` ASC) VISIBLE,
  CONSTRAINT `fk_viagem_motorista1`
    FOREIGN KEY (`motorista_id`)
    REFERENCES `taxi`.`motorista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `taxi`.`motorista`
-- -----------------------------------------------------
START TRANSACTION;
USE `taxi`;
INSERT INTO `taxi`.`motorista` (`id`, `nome`, `descricao`, `carro`, `avaliacao`, `taxa`, `km_minimo`) VALUES (1, 'Homer Simpson', 'Um motorista simpático e descontraído,a experiência é única e o preço é bem acessível.', 'Plymouth Valiant 1973 rosa e enferrujado', '2/5 O motorista é muito desatento!', 2.5, 1);
INSERT INTO `taxi`.`motorista` (`id`, `nome`, `descricao`, `carro`, `avaliacao`, `taxa`, `km_minimo`) VALUES (2, 'Dominic Toretto', 'Sou um profissional gente boa e dono de um carro bem arrumado!', 'Dodge Charger R/T 1970 modificado', '4/5 Não dei nota máxima por conta da modificação do carro rsrsrs!', 5, 5);
INSERT INTO `taxi`.`motorista` (`id`, `nome`, `descricao`, `carro`, `avaliacao`, `taxa`, `km_minimo`) VALUES (3, 'James Bond', 'Motorista muito experiente e super atencioso com o seus clientes!', 'Aston Martin DB5 clássico', '5/5 Gostei do motorista,muito prestativo!', 10, 10);

COMMIT;
